# Generated by Django 2.0.3 on 2018-04-09 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('receipent', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(related_name='_message_users_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
