# Generated by Django 2.0.3 on 2018-04-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='users',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
