# Generated by Django 2.0.6 on 2019-04-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
