# Generated by Django 2.0.3 on 2018-04-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receipent',
            new_name='reciepent',
        ),
    ]
