# Generated by Django 2.0.6 on 2019-04-11 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_conversations_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversations',
            name='last_message',
        ),
        migrations.AddField(
            model_name='conversations',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='message.Message'),
        ),
    ]
