# Generated by Django 2.0.4 on 2018-04-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20180411_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
