# Generated by Django 2.0.3 on 2018-04-11 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='is_liked',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Post'),
        ),
    ]
