# Generated by Django 2.0.3 on 2018-04-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180411_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='is_liked',
            name='post',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
