# Generated by Django 2.0.3 on 2018-04-11 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180411_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='is_liked',
            old_name='post',
            new_name='the_post',
        ),
    ]
