# Generated by Django 2.0.3 on 2018-04-11 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180411_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='is_liked',
            name='user',
        ),
        migrations.DeleteModel(
            name='is_liked',
        ),
    ]
