# Generated by Django 2.0.3 on 2018-04-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_liking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liking',
            name='post',
            field=models.ManyToManyField(to='home.Post'),
        ),
    ]
