# Generated by Django 2.0.4 on 2018-04-17 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_auto_20180412_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liking',
            name='post',
        ),
        migrations.RemoveField(
            model_name='liking',
            name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='number_of_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='user_like',
            field=models.ManyToManyField(related_name='_post_user_like_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Liking',
        ),
    ]
