# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20180418_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='media/profile_image/whatsapponpc.png', upload_to='profile_image'),
        ),
    ]
