# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20180509_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, default='profile_image/whatsapponpc.png', upload_to='profile_image'),
        ),
    ]
