# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20180515_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_pictures',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
