# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20180515_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_pictures',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
